import {ComponentType} from 'react';
import dynamic from 'next/dynamic';

import type {TemplateProps} from '../types';
import {formatComponentCode} from '../utils/helper';

import {about1Code} from './about-1/meta';
import {about2Code} from './about-2/meta';
import {about3Code} from './about-3/meta';
import {about4Code} from './about-4/meta';
import {about5Code} from './about-5/meta';
import {about6Code} from './about-6/meta';
import {about7Code} from './about-7/meta';
import {about8Code} from './about-8/meta';
import {about9Code} from './about-9/meta';
import {about10Code} from './about-10/meta';
import {about11Code} from './about-11/meta';
import {about12Code} from './about-12/meta';
import {about13Code} from './about-13/meta';
import {about14Code} from './about-14/meta';
import {about15Code} from './about-15/meta';
import {about16Code} from './about-16/meta';
import {about17Code} from './about-17/meta';
import {about18Code} from './about-18/meta';
import {about19Code} from './about-19/meta';
import {about20Code} from './about-20/meta';
import {about21Code} from './about-21/meta';
import {about22Code} from './about-22/meta';
import {about23Code} from './about-23/meta';
import {about24Code} from './about-24/meta';
import {about25Code} from './about-25/meta';
import {blog1Code} from './blog-1/meta';
import {blog2Code} from './blog-2/meta';
import {blog3Code} from './blog-3/meta';
import {blog4Code} from './blog-4/meta';
import {blog5Code} from './blog-5/meta';
import {banner1Code} from './banner-1/meta';
import {banner2Code} from './banner-2/meta';
import {banner3Code} from './banner-3/meta';
import {banner5Code} from './banner-5/meta';
import {banner6Code} from './banner-6/meta';
import {clientlist1Code} from './clientlist-1/meta';
import {clientlist2Code} from './clientlist-2/meta';
import {clientlist3Code} from './clientlist-3/meta';
import {clientlist4Code} from './clientlist-4/meta';
import {clientlist5Code} from './clientlist-5/meta';
import {contact1Code} from './contact-1/meta';
import {contact2Code} from './contact-2/meta';
import {contact3Code} from './contact-3/meta';
import {contact4Code} from './contact-4/meta';
import {contact5Code} from './contact-5/meta';
import {contact6Code} from './contact-6/meta';
import {contact7Code} from './contact-7/meta';
import {contact8Code} from './contact-8/meta';
import {contact9Code} from './contact-9/meta';
import {contact10Code} from './contact-10/meta';
import {contact11Code} from './contact-11/meta';
import {contact12Code} from './contact-12/meta';
import {cta1Code} from './cta-1/meta';
import {cta2Code} from './cta-2/meta';
import {cta3Code} from './cta-3/meta';
import {cta4Code} from './cta-4/meta';
import {cta5Code} from './cta-5/meta';
import {cta6Code} from './cta-6/meta';
import {cta7Code} from './cta-7/meta';
import {cta8Code} from './cta-8/meta';
import {cta9Code} from './cta-9/meta';
import {facts1Code} from './facts-1/meta';
import {facts2Code} from './facts-2/meta';
import {facts3Code} from './facts-3/meta';
import {facts4Code} from './facts-4/meta';
import {facts5Code} from './facts-5/meta';
import {facts6Code} from './facts-6/meta';
import {facts7Code} from './facts-7/meta';
import {facts8Code} from './facts-8/meta';
import {facts9Code} from './facts-9/meta';
import {facts10Code} from './facts-10/meta';
import {facts11Code} from './facts-11/meta';
import {facts12Code} from './facts-12/meta';
import {facts13Code} from './facts-13/meta';
import {facts14Code} from './facts-14/meta';
import {facts15Code} from './facts-15/meta';
import {facts16Code} from './facts-16/meta';
import {facts17Code} from './facts-17/meta';
import {faq1Code} from './faq-1/meta';
import {faq2Code} from './faq-2/meta';
import {faq3Code} from './faq-3/meta';
import {faq4Code} from './faq-4/meta';
import {faq5Code} from './faq-5/meta';
import {faq6Code} from './faq-6/meta';
import {footer1Code} from './footer-1/meta';
import {footer2Code} from './footer-2/meta';
import {footer3Code} from './footer-3/meta';
import {footer4Code} from './footer-4/meta';
import {footer5Code} from './footer-5/meta';
import {footer6Code} from './footer-6/meta';
import {footer7Code} from './footer-7/meta';
import {footer8Code} from './footer-8/meta';
import {footer9Code} from './footer-9/meta';
import {footer10Code} from './footer-10/meta';
import {footer11Code} from './footer-11/meta';
import {footer12Code} from './footer-12/meta';
import {footer13Code} from './footer-13/meta';
import {footer14Code} from './footer-14/meta';
import {footer15Code} from './footer-15/meta';
import {hero1Code} from './hero-1/meta';
import {hero2Code} from './hero-2/meta';
import {hero3Code} from './hero-3/meta';
import {hero4Code} from './hero-4/meta';
import {hero5Code} from './hero-5/meta';
import {hero6Code} from './hero-6/meta';
import {hero7Code} from './hero-7/meta';
import {hero8Code} from './hero-8/meta';
import {hero9Code} from './hero-9/meta';
import {hero10Code} from './hero-10/meta';
import {hero11Code} from './hero-11/meta';
import {hero12Code} from './hero-12/meta';
import {hero13Code} from './hero-13/meta';
import {hero14Code} from './hero-14/meta';
import {hero15Code} from './hero-15/meta';
import {hero16Code} from './hero-16/meta';
import {hero17Code} from './hero-17/meta';
import {hero18Code} from './hero-18/meta';
import {hero19Code} from './hero-19/meta';
import {hero20Code} from './hero-20/meta';
import {hero21Code} from './hero-21/meta';
import {hero22Code} from './hero-22/meta';
import {hero23Code} from './hero-23/meta';
import {hero24Code} from './hero-24/meta';
import {hr1Code} from './hr-1/meta';
import {navbar1Code} from './navbar-1/meta';
import {pageProgress1Code} from './page-progress-1/meta';
import {pricing1Code} from './pricing-1/meta';
import {pricing2Code} from './pricing-2/meta';
import {pricing3Code} from './pricing-3/meta';
import {pricing4Code} from './pricing-4/meta';
import {pricing5Code} from './pricing-5/meta';
import {pricing6Code} from './pricing-6/meta';
import {pricing7Code} from './pricing-7/meta';
import {pricing8Code} from './pricing-8/meta';
import {portfolio1Code} from './portfolio-1/meta';
import {portfolio2Code} from './portfolio-2/meta';
import {portfolio3Code} from './portfolio-3/meta';
import {portfolio4Code} from './portfolio-4/meta';
import {portfolio5Code} from './portfolio-5/meta';
import {portfolio6Code} from './portfolio-6/meta';
import {portfolio7Code} from './portfolio-7/meta';
import {portfolio8Code} from './portfolio-8/meta';
import {portfolio9Code} from './portfolio-9/meta';
import {portfolio10Code} from './portfolio-10/meta';
import {portfolio11Code} from './portfolio-11/meta';
import {portfolio12Code} from './portfolio-12/meta';
import {process1Code} from './process-1/meta';
import {process2Code} from './process-2/meta';
import {process3Code} from './process-3/meta';
import {process4Code} from './process-4/meta';
import {process5Code} from './process-5/meta';
import {process6Code} from './process-6/meta';
import {process7Code} from './process-7/meta';
import {process9Code} from './process-9/meta';
import {process10Code} from './process-10/meta';
import {process11Code} from './process-11/meta';
import {process12Code} from './process-12/meta';
import {process13Code} from './process-13/meta';
import {process14Code} from './process-14/meta';
import {process15Code} from './process-15/meta';
import {service1Code} from './service-1/meta';
import {service2Code} from './service-2/meta';
import {service3Code} from './service-3/meta';
import {service4Code} from './service-4/meta';
import {service5Code} from './service-5/meta';
import {service6Code} from './service-6/meta';
import {service7Code} from './service-7/meta';
import {service8Code} from './service-8/meta';
import {service9Code} from './service-9/meta';
import {service10Code} from './service-10/meta';
import {service11Code} from './service-11/meta';
import {service12Code} from './service-12/meta';
import {service13Code} from './service-13/meta';
import {service14Code} from './service-14/meta';
import {service15Code} from './service-15/meta';
import {service16Code} from './service-16/meta';
import {service17Code} from './service-17/meta';
import {service18Code} from './service-18/meta';
import {service19Code} from './service-19/meta';
import {service20Code} from './service-20/meta';
import {service21Code} from './service-21/meta';
import {service22Code} from './service-22/meta';
import {service23Code} from './service-23/meta';
import {service24Code} from './service-24/meta';
import {service25Code} from './service-25/meta';
import {service26Code} from './service-26/meta';
import {service27Code} from './service-27/meta';
import {sidebarMenu1Code} from './sidebar-menu-1/meta';
import {team1Code} from './team-1/meta';
import {team2Code} from './team-2/meta';
import {team3Code} from './team-3/meta';
import {team4Code} from './team-4/meta';
import {team5Code} from './team-5/meta';
import {team6Code} from './team-6/meta';
import {team7Code} from './team-7/meta';
import {testimonial1Code} from './testimonial-1/meta';
import {testimonial2Code} from './testimonial-2/meta';
import {testimonial3Code} from './testimonial-3/meta';
import {testimonial4Code} from './testimonial-4/meta';
import {testimonial5Code} from './testimonial-5/meta';
import {testimonial6Code} from './testimonial-6/meta';
import {testimonial7Code} from './testimonial-7/meta';
import {testimonial8Code} from './testimonial-8/meta';
import {testimonial9Code} from './testimonial-9/meta';
import {testimonial10Code} from './testimonial-10/meta';
import {testimonial11Code} from './testimonial-11/meta';
import {testimonial12Code} from './testimonial-12/meta';
import {testimonial13Code} from './testimonial-13/meta';
import {testimonial14Code} from './testimonial-14/meta';
import {testimonial15Code} from './testimonial-15/meta';
import {testimonial16Code} from './testimonial-16/meta';
import {testimonial17Code} from './testimonial-17/meta';
import {testimonial18Code} from './testimonial-18/meta';
import {testimonial19Code} from './testimonial-19/meta';
import {wiki1Code} from './wiki-1/meta';

const componentMap: Record<string, ComponentType<TemplateProps>> = {
  [about1Code]: dynamic(() => import('./about-1')),
  [about2Code]: dynamic(() => import('./about-2')),
  [about3Code]: dynamic(() => import('./about-3')),
  [about4Code]: dynamic(() => import('./about-4')),
  [about5Code]: dynamic(() => import('./about-5')),
  [about6Code]: dynamic(() => import('./about-6')),
  [about7Code]: dynamic(() => import('./about-7')),
  [about8Code]: dynamic(() => import('./about-8')),
  [about9Code]: dynamic(() => import('./about-9')),
  [about10Code]: dynamic(() => import('./about-10')),
  [about11Code]: dynamic(() => import('./about-11')),
  [about12Code]: dynamic(() => import('./about-12')),
  [about13Code]: dynamic(() => import('./about-13')),
  [about14Code]: dynamic(() => import('./about-14')),
  [about15Code]: dynamic(() => import('./about-15')),
  [about16Code]: dynamic(() => import('./about-16')),
  [about17Code]: dynamic(() => import('./about-17')),
  [about18Code]: dynamic(() => import('./about-18')),
  [about19Code]: dynamic(() => import('./about-19')),
  [about20Code]: dynamic(() => import('./about-20')),
  [about21Code]: dynamic(() => import('./about-21')),
  [about22Code]: dynamic(() => import('./about-22')),
  [about23Code]: dynamic(() => import('./about-23')),
  [about24Code]: dynamic(() => import('./about-24')),
  [about25Code]: dynamic(() => import('./about-25')),
  [blog1Code]: dynamic(() => import('./blog-1')),
  [blog2Code]: dynamic(() => import('./blog-2')),
  [blog3Code]: dynamic(() => import('./blog-3')),
  [blog4Code]: dynamic(() => import('./blog-4')),
  [blog5Code]: dynamic(() => import('./blog-5')),
  [banner1Code]: dynamic(() => import('./banner-1')),
  [banner2Code]: dynamic(() => import('./banner-2')),
  [banner3Code]: dynamic(() => import('./banner-3')),
  [banner5Code]: dynamic(() => import('./banner-5')),
  [banner6Code]: dynamic(() => import('./banner-6')),
  [hero1Code]: dynamic(() => import('./hero-1')),
  [hero2Code]: dynamic(() => import('./hero-2')),
  [hero3Code]: dynamic(() => import('./hero-3')),
  [hero4Code]: dynamic(() => import('./hero-4')),
  [hero5Code]: dynamic(() => import('./hero-5')),
  [hero6Code]: dynamic(() => import('./hero-6')),
  [hero7Code]: dynamic(() => import('./hero-7')),
  [hero8Code]: dynamic(() => import('./hero-8')),
  [hero9Code]: dynamic(() => import('./hero-9')),
  [hero10Code]: dynamic(() => import('./hero-10')),
  [hero11Code]: dynamic(() => import('./hero-11')),
  [hero12Code]: dynamic(() => import('./hero-12')),
  [hero13Code]: dynamic(() => import('./hero-13')),
  [hero14Code]: dynamic(() => import('./hero-14')),
  [hero15Code]: dynamic(() => import('./hero-15')),
  [hero16Code]: dynamic(() => import('./hero-16')),
  [hero17Code]: dynamic(() => import('./hero-17')),
  [hero18Code]: dynamic(() => import('./hero-18')),
  [hero19Code]: dynamic(() => import('./hero-19')),
  [hero20Code]: dynamic(() => import('./hero-20')),
  [hero21Code]: dynamic(() => import('./hero-21')),
  [hero22Code]: dynamic(() => import('./hero-22')),
  [hero23Code]: dynamic(() => import('./hero-23')),
  [hero24Code]: dynamic(() => import('./hero-24')),
  [hr1Code]: dynamic(() => import('./hr-1')),
  [pageProgress1Code]: dynamic(() => import('./page-progress-1')),
  [cta1Code]: dynamic(() => import('./cta-1')),
  [cta2Code]: dynamic(() => import('./cta-2')),
  [cta3Code]: dynamic(() => import('./cta-3')),
  [cta4Code]: dynamic(() => import('./cta-4')),
  [cta5Code]: dynamic(() => import('./cta-5')),
  [cta6Code]: dynamic(() => import('./cta-6')),
  [cta7Code]: dynamic(() => import('./cta-7')),
  [cta8Code]: dynamic(() => import('./cta-8')),
  [cta9Code]: dynamic(() => import('./cta-9')),
  [facts1Code]: dynamic(() => import('./facts-1')),
  [facts2Code]: dynamic(() => import('./facts-2')),
  [facts3Code]: dynamic(() => import('./facts-3')),
  [facts4Code]: dynamic(() => import('./facts-4')),
  [facts5Code]: dynamic(() => import('./facts-5')),
  [facts6Code]: dynamic(() => import('./facts-6')),
  [facts7Code]: dynamic(() => import('./facts-7')),
  [facts8Code]: dynamic(() => import('./facts-8')),
  [facts9Code]: dynamic(() => import('./facts-9')),
  [facts10Code]: dynamic(() => import('./facts-10')),
  [facts11Code]: dynamic(() => import('./facts-11')),
  [facts12Code]: dynamic(() => import('./facts-12')),
  [facts13Code]: dynamic(() => import('./facts-13')),
  [facts14Code]: dynamic(() => import('./facts-14')),
  [facts15Code]: dynamic(() => import('./facts-15')),
  [facts16Code]: dynamic(() => import('./facts-16')),
  [facts17Code]: dynamic(() => import('./facts-17')),
  [faq1Code]: dynamic(() => import('./faq-1')),
  [faq2Code]: dynamic(() => import('./faq-2')),
  [faq3Code]: dynamic(() => import('./faq-3')),
  [faq4Code]: dynamic(() => import('./faq-4')),
  [faq5Code]: dynamic(() => import('./faq-5')),
  [faq6Code]: dynamic(() => import('./faq-6')),
  [process1Code]: dynamic(() => import('./process-1')),
  [process2Code]: dynamic(() => import('./process-2')),
  [process3Code]: dynamic(() => import('./process-3')),
  [process4Code]: dynamic(() => import('./process-4')),
  [process5Code]: dynamic(() => import('./process-5')),
  [process6Code]: dynamic(() => import('./process-6')),
  [process7Code]: dynamic(() => import('./process-7')),
  [process9Code]: dynamic(() => import('./process-9')),
  [process10Code]: dynamic(() => import('./process-10')),
  [process11Code]: dynamic(() => import('./process-11')),
  [process12Code]: dynamic(() => import('./process-12')),
  [process13Code]: dynamic(() => import('./process-13')),
  [process14Code]: dynamic(() => import('./process-14')),
  [process15Code]: dynamic(() => import('./process-15')),
  [team1Code]: dynamic(() => import('./team-1')),
  [team2Code]: dynamic(() => import('./team-2')),
  [team3Code]: dynamic(() => import('./team-3')),
  [team4Code]: dynamic(() => import('./team-4')),
  [team5Code]: dynamic(() => import('./team-5')),
  [team6Code]: dynamic(() => import('./team-6')),
  [team7Code]: dynamic(() => import('./team-7')),
  [service1Code]: dynamic(() => import('./service-1')),
  [service2Code]: dynamic(() => import('./service-2')),
  [service3Code]: dynamic(() => import('./service-3')),
  [service4Code]: dynamic(() => import('./service-4')),
  [service5Code]: dynamic(() => import('./service-5')),
  [service6Code]: dynamic(() => import('./service-6')),
  [service7Code]: dynamic(() => import('./service-7')),
  [service8Code]: dynamic(() => import('./service-8')),
  [service9Code]: dynamic(() => import('./service-9')),
  [service10Code]: dynamic(() => import('./service-10')),
  [service11Code]: dynamic(() => import('./service-11')),
  [service12Code]: dynamic(() => import('./service-12')),
  [service13Code]: dynamic(() => import('./service-13')),
  [service14Code]: dynamic(() => import('./service-14')),
  [service15Code]: dynamic(() => import('./service-15')),
  [service16Code]: dynamic(() => import('./service-16')),
  [service17Code]: dynamic(() => import('./service-17')),
  [service18Code]: dynamic(() => import('./service-18')),
  [service19Code]: dynamic(() => import('./service-19')),
  [service20Code]: dynamic(() => import('./service-20')),
  [service21Code]: dynamic(() => import('./service-21')),
  [service22Code]: dynamic(() => import('./service-22')),
  [service23Code]: dynamic(() => import('./service-23')),
  [service24Code]: dynamic(() => import('./service-24')),
  [service25Code]: dynamic(() => import('./service-25')),
  [service26Code]: dynamic(() => import('./service-26')),
  [service27Code]: dynamic(() => import('./service-27')),
  [testimonial1Code]: dynamic(() => import('./testimonial-1')),
  [testimonial2Code]: dynamic(() => import('./testimonial-2')),
  [testimonial3Code]: dynamic(() => import('./testimonial-3')),
  [testimonial4Code]: dynamic(() => import('./testimonial-4')),
  [testimonial5Code]: dynamic(() => import('./testimonial-5')),
  [testimonial6Code]: dynamic(() => import('./testimonial-6')),
  [testimonial7Code]: dynamic(() => import('./testimonial-7')),
  [testimonial8Code]: dynamic(() => import('./testimonial-8')),
  [testimonial9Code]: dynamic(() => import('./testimonial-9')),
  [testimonial10Code]: dynamic(() => import('./testimonial-10')),
  [testimonial11Code]: dynamic(() => import('./testimonial-11')),
  [testimonial12Code]: dynamic(() => import('./testimonial-12')),
  [testimonial13Code]: dynamic(() => import('./testimonial-13')),
  [testimonial14Code]: dynamic(() => import('./testimonial-14')),
  [testimonial15Code]: dynamic(() => import('./testimonial-15')),
  [testimonial16Code]: dynamic(() => import('./testimonial-16')),
  [testimonial17Code]: dynamic(() => import('./testimonial-17')),
  [testimonial18Code]: dynamic(() => import('./testimonial-18')),
  [testimonial19Code]: dynamic(() => import('./testimonial-19')),
  [pricing1Code]: dynamic(() => import('./pricing-1')),
  [pricing2Code]: dynamic(() => import('./pricing-2')),
  [pricing3Code]: dynamic(() => import('./pricing-3')),
  [pricing4Code]: dynamic(() => import('./pricing-4')),
  [pricing5Code]: dynamic(() => import('./pricing-5')),
  [pricing6Code]: dynamic(() => import('./pricing-6')),
  [pricing7Code]: dynamic(() => import('./pricing-7')),
  [pricing8Code]: dynamic(() => import('./pricing-8')),
  [portfolio1Code]: dynamic(() => import('./portfolio-1')),
  [portfolio2Code]: dynamic(() => import('./portfolio-2')),
  [portfolio3Code]: dynamic(() => import('./portfolio-3')),
  [portfolio4Code]: dynamic(() => import('./portfolio-4')),
  [portfolio5Code]: dynamic(() => import('./portfolio-5')),
  [portfolio6Code]: dynamic(() => import('./portfolio-6')),
  [portfolio7Code]: dynamic(() => import('./portfolio-7')),
  [portfolio8Code]: dynamic(() => import('./portfolio-8')),
  [portfolio9Code]: dynamic(() => import('./portfolio-9')),
  [portfolio10Code]: dynamic(() => import('./portfolio-10')),
  [portfolio11Code]: dynamic(() => import('./portfolio-11')),
  [portfolio12Code]: dynamic(() => import('./portfolio-12')),
  [contact1Code]: dynamic(() => import('./contact-1')),
  [contact2Code]: dynamic(() => import('./contact-2')),
  [contact3Code]: dynamic(() => import('./contact-3')),
  [contact4Code]: dynamic(() => import('./contact-4')),
  [contact5Code]: dynamic(() => import('./contact-5')),
  [contact6Code]: dynamic(() => import('./contact-6')),
  [contact7Code]: dynamic(() => import('./contact-7')),
  [contact8Code]: dynamic(() => import('./contact-8')),
  [contact9Code]: dynamic(() => import('./contact-9')),
  [contact10Code]: dynamic(() => import('./contact-10')),
  [contact11Code]: dynamic(() => import('./contact-11')),
  [contact12Code]: dynamic(() => import('./contact-12')),
  [clientlist1Code]: dynamic(() => import('./clientlist-1')),
  [clientlist2Code]: dynamic(() => import('./clientlist-2')),
  [clientlist3Code]: dynamic(() => import('./clientlist-3')),
  [clientlist4Code]: dynamic(() => import('./clientlist-4')),
  [clientlist5Code]: dynamic(() => import('./clientlist-5')),
  [navbar1Code]: dynamic(() => import('./navbar-1')),
  [footer1Code]: dynamic(() => import('./footer-1')),
  [footer2Code]: dynamic(() => import('./footer-2')),
  [footer3Code]: dynamic(() => import('./footer-3')),
  [footer4Code]: dynamic(() => import('./footer-4')),
  [footer5Code]: dynamic(() => import('./footer-5')),
  [footer6Code]: dynamic(() => import('./footer-6')),
  [footer7Code]: dynamic(() => import('./footer-7')),
  [footer8Code]: dynamic(() => import('./footer-8')),
  [footer9Code]: dynamic(() => import('./footer-9')),
  [footer10Code]: dynamic(() => import('./footer-10')),
  [footer11Code]: dynamic(() => import('./footer-11')),
  [footer12Code]: dynamic(() => import('./footer-12')),
  [footer13Code]: dynamic(() => import('./footer-13')),
  [footer14Code]: dynamic(() => import('./footer-14')),
  [footer15Code]: dynamic(() => import('./footer-15')),
  [wiki1Code]: dynamic(() => import('./wiki-1'), {ssr: false}),
  [sidebarMenu1Code]: dynamic(() => import('./sidebar-menu-1')),
};

export const ComponentMap = Object.fromEntries(
  Object.entries(componentMap).map(([key, value]) => [
    formatComponentCode(key),
    value,
  ]),
) as Record<string, ComponentType<TemplateProps>>;
