export {Informations} from './informations';
export {Total} from './total';
export {Contact} from './contact';
export {Products} from './products';
export {PaymentMethod} from './payment-method';
export {History} from './history';
export {ContactUs} from './contact-us';
export {ProductCard} from './product-card';
export {OrderColumns} from './columns';
