export const HOST =
  process.env.MATTERMOST_HOST ||
  process.env.NEXT_PUBLIC_MATTERMOST_HOST ||
  process.env.VITE_MATTERMOST_HOST;

export const WEBSOCKET_URL =
  process.env.MATTERMOST_WEBSOCKET_URL ||
  process.env.NEXT_PUBLIC_MATTERMOST_WEBSOCKET_URL ||
  process.env.VITE_MATTERMOST_WEBSOCKET_URL;

export const SocketEvents = {
  POSTED: 'posted',
  POST_EDITED: 'post_edited',
  POST_DELETED: 'post_deleted',
  POST_UPDATED: 'post_updated',
  POST_UNREAD: 'post_unread',
  CHANNEL_CONVERTED: 'channel_converted',
  CHANNEL_CREATED: 'channel_created',
  CHANNEL_DELETED: 'channel_deleted',
  CHANNEL_UNARCHIVED: 'channel_restored',
  CHANNEL_UPDATED: 'channel_updated',
  MULTIPLE_CHANNELS_VIEWED: 'multiple_channels_viewed',
  CHANNEL_MEMBER_UPDATED: 'channel_member_updated',
  CHANNEL_SCHEME_UPDATED: 'channel_scheme_updated',
  DIRECT_ADDED: 'direct_added',
  GROUP_ADDED: 'group_added',
  NEW_USER: 'new_user',
  ADDED_TO_TEAM: 'added_to_team',
  JOIN_TEAM: 'join_team',
  LEAVE_TEAM: 'leave_team',
  UPDATE_TEAM: 'update_team',
  DELETE_TEAM: 'delete_team',
  UPDATE_TEAM_SCHEME: 'update_team_scheme',
  USER_ADDED: 'user_added',
  USER_REMOVED: 'user_removed',
  USER_UPDATED: 'user_updated',
  USER_ROLE_UPDATED: 'user_role_updated',
  MEMBERROLE_UPDATED: 'memberrole_updated',
  ROLE_ADDED: 'role_added',
  ROLE_REMOVED: 'role_removed',
  ROLE_UPDATED: 'role_updated',
  TYPING: 'typing',
  PREFERENCE_CHANGED: 'preference_changed',
  PREFERENCES_CHANGED: 'preferences_changed',
  PREFERENCES_DELETED: 'preferences_deleted',
  EPHEMERAL_MESSAGE: 'ephemeral_message',
  STATUS_CHANGED: 'status_change',
  HELLO: 'hello',
  REACTION_ADDED: 'reaction_added',
  REACTION_REMOVED: 'reaction_removed',
  EMOJI_ADDED: 'emoji_added',
  PLUGIN_ENABLED: 'plugin_enabled',
  PLUGIN_DISABLED: 'plugin_disabled',
  LICENSE_CHANGED: 'license_changed',
  CONFIG_CHANGED: 'config_changed',
  PLUGIN_STATUSES_CHANGED: 'plugin_statuses_changed',
  OPEN_DIALOG: 'open_dialog',
  RECEIVED_GROUP: 'received_group',
  GROUP_MEMBER_ADD: 'group_member_add',
  GROUP_MEMBER_DELETED: 'group_member_deleted',
  RECEIVED_GROUP_ASSOCIATED_TO_TEAM: 'received_group_associated_to_team',
  RECEIVED_GROUP_NOT_ASSOCIATED_TO_TEAM:
    'received_group_not_associated_to_team',
  RECEIVED_GROUP_ASSOCIATED_TO_CHANNEL: 'received_group_associated_to_channel',
  RECEIVED_GROUP_NOT_ASSOCIATED_TO_CHANNEL:
    'received_group_not_associated_to_channel',
  WARN_METRIC_STATUS_RECEIVED: 'warn_metric_status_received',
  WARN_METRIC_STATUS_REMOVED: 'warn_metric_status_removed',
  SIDEBAR_CATEGORY_CREATED: 'sidebar_category_created',
  SIDEBAR_CATEGORY_UPDATED: 'sidebar_category_updated',
  SIDEBAR_CATEGORY_DELETED: 'sidebar_category_deleted',
  SIDEBAR_CATEGORY_ORDER_UPDATED: 'sidebar_category_order_updated',
  USER_ACTIVATION_STATUS_CHANGED: 'user_activation_status_change',
  CLOUD_PAYMENT_STATUS_UPDATED: 'cloud_payment_status_updated',
  CLOUD_SUBSCRIPTION_CHANGED: 'cloud_subscription_changed',
  APPS_FRAMEWORK_REFRESH_BINDINGS:
    'custom_com.mattermost.apps_refresh_bindings',
  APPS_FRAMEWORK_PLUGIN_ENABLED: 'custom_com.mattermost.apps_plugin_enabled',
  APPS_FRAMEWORK_PLUGIN_DISABLED: 'custom_com.mattermost.apps_plugin_disabled',
  FIRST_ADMIN_VISIT_MARKETPLACE_STATUS_RECEIVED:
    'first_admin_visit_marketplace_status_received',
  THREAD_UPDATED: 'thread_updated',
  THREAD_FOLLOW_CHANGED: 'thread_follow_changed',
  THREAD_READ_CHANGED: 'thread_read_changed',
  POST_ACKNOWLEDGEMENT_ADDED: 'post_acknowledgement_added',
  POST_ACKNOWLEDGEMENT_REMOVED: 'post_acknowledgement_removed',
  DRAFT_CREATED: 'draft_created',
  DRAFT_UPDATED: 'draft_updated',
  DRAFT_DELETED: 'draft_deleted',
  PERSISTENT_NOTIFICATION_TRIGGERED: 'persistent_notification_triggered',
  HOSTED_CUSTOMER_SIGNUP_PROGRESS_UPDATED:
    'hosted_customer_signup_progress_updated',
};

export const emojis: {[key: string]: string} = {
  joy: '1f602.png',
  heart: '2764-fe0f.png',
  '+1': '1f44d.png',
  innocent: '1f607.png',
  heart_eyes: '1f60d.png',
  rolling_on_the_floor_laughing: '1f923.png',
  kissing_heart: '1f618.png',
  upside_down_face: '1f643.png',
  pensive: '1f614.png',
  slightly_smiling_face: '1f642.png',
  face_with_raised_eyebrow: '1f928.png',
  smiley: '1f603.png',
  smiling_face_with_3_hearts: '1f970.png',
  cry: '1f622.png',
  sob: '1f62d.png',
  broken_heart: '1f494.png',
  handshake: '1f91d.png',
};

export const DEFAULT_CHANNEL = 'Town Square';
