import {
  Template,
  type Data,
  type Demo,
  type TemplateSchema,
} from '../../types/templates';
import {metaFileModel} from '../meta-models';

export const portfolio5Schema = {
  title: 'Portfolio 5',
  code: 'portfolio5',
  type: Template.block,
  fields: [
    {
      name: 'description',
      title: 'Description',
      type: 'string',
    },
    {
      name: 'caption',
      title: 'Caption',
      type: 'string',
    },
    {
      name: 'list',
      title: 'List',
      type: 'json-one-to-many',
      target: 'Portfolio5List',
    },
    {
      name: 'filterList',
      title: 'Filter List',
      type: 'json-one-to-many',
      target: 'Portfolio5FilterList',
    },
    {
      name: 'wrapperClassName',
      title: 'Wrapper Class Name',
      type: 'string',
      defaultValue: 'wrapper bg-gray',
    },
    {
      name: 'containerClassName',
      title: 'Container Class Name',
      type: 'string',
      defaultValue: 'container py-15 py-md-17 text-center',
    },
  ],
  models: [
    {
      name: 'Portfolio5List',
      title: 'List',
      fields: [
        {
          name: 'value',
          title: 'Value',
          type: 'string',
        },
        {
          name: 'title',
          title: 'Title',
          type: 'string',
          nameField: true,
          visibleInGrid: true,
        },
      ],
    },
    {
      name: 'Portfolio5FilterList',
      title: 'Filter List',
      fields: [
        {
          name: 'image',
          title: 'Image',
          type: 'many-to-one',
          target: 'com.axelor.meta.db.MetaFile',
          widget: 'Image',
        },
        {
          name: 'imageWidth',
          title: 'Image Width',
          type: 'integer',
        },
        {
          name: 'imageHeight',
          title: 'Image Height',
          type: 'integer',
        },
        {
          name: 'fullImage',
          title: 'Full Image',
          type: 'many-to-one',
          target: 'com.axelor.meta.db.MetaFile',
          widget: 'Image',
        },
        {
          name: 'category',
          title: 'Category',
          type: 'string',
        },
        {
          name: 'title',
          title: 'Title',
          type: 'string',
          nameField: true,
          visibleInGrid: true,
        },
      ],
    },
  ],
  metaModels: [metaFileModel],
} as const satisfies TemplateSchema;

export type Portfolio5Data = Data<typeof portfolio5Schema>;

export const portfolio5Demos: Demo<typeof portfolio5Schema>[] = [
  {
    language: 'en_US',
    page: 'demo-24',
    sequence: 4,
    data: {
      portfolio5Description:
        'My interest is taking pictures, and I enjoy transforming thoughts into lovely things.',
      portfolio5Caption: 'My Recent Photographs',
      portfolio5List: [
        {id: '1', version: 0, attrs: {title: 'All', value: '*'}},
        {id: '2', version: 0, attrs: {title: 'Foods', value: '.foods'}},
        {id: '3', version: 0, attrs: {title: 'Drinks', value: '.drinks'}},
        {id: '4', version: 0, attrs: {title: 'Events', value: '.events'}},
        {id: '5', version: 0, attrs: {title: 'Pastries', value: '.pastries'}},
      ],
      portfolio5FilterList: [
        {
          id: '1',
          version: 0,
          attrs: {
            title: 'Fringilla Nullam',
            category: 'drinks events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf1.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf1.jpg',
            },
            imageWidth: 380,
            imageHeight: 254,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf1-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf1-full.jpg',
            },
          },
        },
        {
          id: '2',
          version: 0,
          attrs: {
            title: 'Ridiculus Parturient',
            category: 'events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf2.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf2.jpg',
            },
            imageWidth: 380,
            imageHeight: 294,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf2-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf2-full.jpg',
            },
          },
        },
        {
          id: '3',
          version: 0,
          attrs: {
            title: 'Ornare Ipsum',
            category: 'pastries events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf3.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf3.jpg',
            },
            imageWidth: 380,
            imageHeight: 502,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf3-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf3-full.jpg',
            },
          },
        },
        {
          id: '4',
          version: 0,
          attrs: {
            title: 'Nullam Mollis',
            category: 'events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf4.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf4.jpg',
            },
            imageWidth: 380,
            imageHeight: 456,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf4-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf4-full.jpg',
            },
          },
        },
        {
          id: '5',
          version: 0,
          attrs: {
            title: 'Euismod Risus',
            category: 'pastries events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf5.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf5.jpg',
            },
            imageWidth: 380,
            imageHeight: 305,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf5-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf5-full.jpg',
            },
          },
        },
        {
          id: '6',
          version: 0,
          attrs: {
            title: 'Ridiculus Tristique',
            category: 'foods',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf6.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf6.jpg',
            },
            imageWidth: 380,
            imageHeight: 253,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf6-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf6-full.jpg',
            },
          },
        },
        {
          id: '7',
          version: 0,
          attrs: {
            title: 'Sollicitudin Pharetra',
            category: 'foods drinks',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf7.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf7.jpg',
            },
            imageWidth: 380,
            imageHeight: 359,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf7-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf7-full.jpg',
            },
          },
        },
        {
          id: '8',
          version: 0,
          attrs: {
            title: 'Tristique Venenatis',
            category: 'pastries',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf8.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf8.jpg',
            },
            imageWidth: 380,
            imageHeight: 254,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf8-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf8-full.jpg',
            },
          },
        },
        {
          id: '9',
          version: 0,
          attrs: {
            title: 'Cursus Fusce',
            category: 'events',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf9.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf9.jpg',
            },
            imageWidth: 380,
            imageHeight: 284,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf9-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf9-full.jpg',
            },
          },
        },
        {
          id: '10',
          version: 0,
          attrs: {
            title: 'Consectetur Malesuada',
            category: 'foods',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf10.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf10.jpg',
            },
            imageWidth: 380,
            imageHeight: 477,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf10-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf10-full.jpg',
            },
          },
        },
        {
          id: '11',
          version: 0,
          attrs: {
            title: 'Ultricies Aenean',
            category: 'drinks',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf11.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf11.jpg',
            },
            imageWidth: 380,
            imageHeight: 274,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf11-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf11-full.jpg',
            },
          },
        },
        {
          id: '12',
          version: 0,
          attrs: {
            title: 'Pellentesque Commodo',
            category: 'foods',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf12.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf12.jpg',
            },
            imageWidth: 380,
            imageHeight: 507,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf12-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf12-full.jpg',
            },
          },
        },
        {
          id: '13',
          version: 0,
          attrs: {
            title: 'Ultricies Aenean',
            category: 'drinks',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf13.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf13.jpg',
            },
            imageWidth: 380,
            imageHeight: 391,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf13-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf13-full.jpg',
            },
          },
        },
      ],
    },
  },
  {
    language: 'fr_FR',
    page: 'demo-24',
    sequence: 4,
    data: {
      portfolio5Description:
        'Mon intérêt est de prendre des photos, et j’aime transformer les pensées en de belles choses.',
      portfolio5Caption: 'Mes photographies récentes',
      portfolio5List: [
        {id: '1', version: 0, attrs: {title: 'Tous', value: '*'}},
        {id: '2', version: 0, attrs: {title: 'Aliments', value: '.foods'}},
        {id: '3', version: 0, attrs: {title: 'Boissons', value: '.drinks'}},
        {id: '4', version: 0, attrs: {title: 'Événements', value: '.events'}},
        {
          id: '5',
          version: 0,
          attrs: {title: 'Pâtisseries', value: '.pastries'},
        },
      ],
      portfolio5FilterList: [
        {
          id: '1',
          version: 0,
          attrs: {
            title: 'Fringilla Nullam',
            category: 'boissons événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf1.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf1.jpg',
            },
            imageWidth: 380,
            imageHeight: 254,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf1-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf1-full.jpg',
            },
          },
        },
        {
          id: '2',
          version: 0,
          attrs: {
            title: 'Ridiculus Parturient',
            category: 'événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf2.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf2.jpg',
            },
            imageWidth: 380,
            imageHeight: 294,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf2-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf2-full.jpg',
            },
          },
        },
        {
          id: '3',
          version: 0,
          attrs: {
            title: 'Ornare Ipsum',
            category: 'pâtisseries événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf3.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf3.jpg',
            },
            imageWidth: 380,
            imageHeight: 502,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf3-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf3-full.jpg',
            },
          },
        },
        {
          id: '4',
          version: 0,
          attrs: {
            title: 'Nullam Mollis',
            category: 'événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf4.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf4.jpg',
            },
            imageWidth: 380,
            imageHeight: 456,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf4-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf4-full.jpg',
            },
          },
        },
        {
          id: '5',
          version: 0,
          attrs: {
            title: 'Euismod Risus',
            category: 'pâtisseries événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf5.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf5.jpg',
            },
            imageWidth: 380,
            imageHeight: 305,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf5-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf5-full.jpg',
            },
          },
        },
        {
          id: '6',
          version: 0,
          attrs: {
            title: 'Ridiculus Tristique',
            category: 'aliments',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf6.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf6.jpg',
            },
            imageWidth: 380,
            imageHeight: 253,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf6-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf6-full.jpg',
            },
          },
        },
        {
          id: '7',
          version: 0,
          attrs: {
            title: 'Sollicitudin Pharetra',
            category: 'aliments boissons',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf7.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf7.jpg',
            },
            imageWidth: 380,
            imageHeight: 359,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf7-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf7-full.jpg',
            },
          },
        },
        {
          id: '8',
          version: 0,
          attrs: {
            title: 'Tristique Venenatis',
            category: 'pâtisseries',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf8.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf8.jpg',
            },
            imageWidth: 380,
            imageHeight: 254,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf8-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf8-full.jpg',
            },
          },
        },
        {
          id: '9',
          version: 0,
          attrs: {
            title: 'Cursus Fusce',
            category: 'événements',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf9.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf9.jpg',
            },
            imageWidth: 380,
            imageHeight: 284,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf9-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf9-full.jpg',
            },
          },
        },
        {
          id: '10',
          version: 0,
          attrs: {
            title: 'Consectetur Malesuada',
            category: 'aliments',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf10.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf10.jpg',
            },
            imageWidth: 380,
            imageHeight: 477,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf10-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf10-full.jpg',
            },
          },
        },
        {
          id: '11',
          version: 0,
          attrs: {
            title: 'Ultricies Aenean',
            category: 'boissons',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf11.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf11.jpg',
            },
            imageWidth: 380,
            imageHeight: 274,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf11-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf11-full.jpg',
            },
          },
        },
        {
          id: '12',
          version: 0,
          attrs: {
            title: 'Pellentesque Commodo',
            category: 'aliments',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf12.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf12.jpg',
            },
            imageWidth: 380,
            imageHeight: 507,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf12-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf12-full.jpg',
            },
          },
        },
        {
          id: '13',
          version: 0,
          attrs: {
            title: 'Ultricies Aenean',
            category: 'boissons',
            image: {
              id: '1',
              version: 1,
              fileName: 'pf13.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf13.jpg',
            },
            imageWidth: 380,
            imageHeight: 391,
            fullImage: {
              id: '1',
              version: 1,
              fileName: 'pf13-full.jpg',
              fileType: 'image/jpeg',
              filePath: '/img/photos/pf13-full.jpg',
            },
          },
        },
      ],
    },
  },
];
